### ISSUE TITLE
whats the correct way to convert non protobuf fields ?

### ISSUE THREAD

**Issue by ymolists** [stripe/skycfg#27]
First thank you so much for open sourcing this tool !

```
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
```

I am trying to convert the above from yaml to skycfg. What would be the correct way of defining `spec.resources.requests` ?
